# interrupt prehandler
intr_vec0:
	cli
	pushl $0
	pushl $0
	jmp _alltraps
.globl intr_vec0
intr_vec1:
	cli
	pushl $0
	pushl $1
	jmp _alltraps
.globl intr_vec1
intr_vec2:
	cli
	pushl $0
	pushl $2
	jmp _alltraps
.globl intr_vec2
intr_vec3:
	cli
	pushl $0
	pushl $3
	jmp _alltraps
.globl intr_vec3
intr_vec4:
	cli
	pushl $0
	pushl $4
	jmp _alltraps
.globl intr_vec4
intr_vec5:
	cli
	pushl $0
	pushl $5
	jmp _alltraps
.globl intr_vec5
intr_vec6:
	cli
	pushl $0
	pushl $6
	jmp _alltraps
.globl intr_vec6
intr_vec7:
	cli
	pushl $0
	pushl $7
	jmp _alltraps
.globl intr_vec7
intr_vec8:
	cli
	pushl $8
	jmp _alltraps
.globl intr_vec8
intr_vec9:
	cli
	pushl $0
	pushl $9
	jmp _alltraps
.globl intr_vec9
intr_vec10:
	cli
	pushl $10
	jmp _alltraps
.globl intr_vec10
intr_vec11:
	cli
	pushl $11
	jmp _alltraps
.globl intr_vec11
intr_vec12:
	cli
	pushl $12
	jmp _alltraps
.globl intr_vec12
intr_vec13:
	cli
	pushl $13
	jmp _alltraps
.globl intr_vec13
intr_vec14:
	cli
	pushl $14
	jmp _alltraps
.globl intr_vec14
intr_vec15:
	cli
	pushl $0
	pushl $15
	jmp _alltraps
.globl intr_vec15
intr_vec16:
	cli
	pushl $0
	pushl $16
	jmp _alltraps
.globl intr_vec16
intr_vec17:
	cli
	pushl $17
	jmp _alltraps
.globl intr_vec17
intr_vec18:
	cli
	pushl $0
	pushl $18
	jmp _alltraps
.globl intr_vec18
intr_vec19:
	cli
	pushl $0
	pushl $19
	jmp _alltraps
.globl intr_vec19
intr_vec20:
	cli
	pushl $0
	pushl $20
	jmp _alltraps
.globl intr_vec20
intr_vec21:
	cli
	pushl $21
	jmp _alltraps
.globl intr_vec21
intr_vec22:
	cli
	pushl $0
	pushl $22
	jmp _alltraps
.globl intr_vec22
intr_vec23:
	cli
	pushl $0
	pushl $23
	jmp _alltraps
.globl intr_vec23
intr_vec24:
	cli
	pushl $0
	pushl $24
	jmp _alltraps
.globl intr_vec24
intr_vec25:
	cli
	pushl $0
	pushl $25
	jmp _alltraps
.globl intr_vec25
intr_vec26:
	cli
	pushl $0
	pushl $26
	jmp _alltraps
.globl intr_vec26
intr_vec27:
	cli
	pushl $0
	pushl $27
	jmp _alltraps
.globl intr_vec27
intr_vec28:
	cli
	pushl $0
	pushl $28
	jmp _alltraps
.globl intr_vec28
intr_vec29:
	cli
	pushl $0
	pushl $29
	jmp _alltraps
.globl intr_vec29
intr_vec30:
	cli
	pushl $0
	pushl $30
	jmp _alltraps
.globl intr_vec30
intr_vec31:
	cli
	pushl $0
	pushl $31
	jmp _alltraps
.globl intr_vec31
intr_vec32:
	cli
	pushl $0
	pushl $32
	jmp _alltraps
.globl intr_vec32
intr_vec33:
	cli
	pushl $0
	pushl $33
	jmp _alltraps
.globl intr_vec33
intr_vec34:
	cli
	pushl $0
	pushl $34
	jmp _alltraps
.globl intr_vec34
intr_vec35:
	cli
	pushl $0
	pushl $35
	jmp _alltraps
.globl intr_vec35
intr_vec36:
	cli
	pushl $0
	pushl $36
	jmp _alltraps
.globl intr_vec36
intr_vec37:
	cli
	pushl $0
	pushl $37
	jmp _alltraps
.globl intr_vec37
intr_vec38:
	cli
	pushl $0
	pushl $38
	jmp _alltraps
.globl intr_vec38
intr_vec39:
	cli
	pushl $0
	pushl $39
	jmp _alltraps
.globl intr_vec39
intr_vec40:
	cli
	pushl $0
	pushl $40
	jmp _alltraps
.globl intr_vec40
intr_vec41:
	cli
	pushl $0
	pushl $41
	jmp _alltraps
.globl intr_vec41
intr_vec42:
	cli
	pushl $0
	pushl $42
	jmp _alltraps
.globl intr_vec42
intr_vec43:
	cli
	pushl $0
	pushl $43
	jmp _alltraps
.globl intr_vec43
intr_vec44:
	cli
	pushl $0
	pushl $44
	jmp _alltraps
.globl intr_vec44
intr_vec45:
	cli
	pushl $0
	pushl $45
	jmp _alltraps
.globl intr_vec45
intr_vec46:
	cli
	pushl $0
	pushl $46
	jmp _alltraps
.globl intr_vec46
intr_vec47:
	cli
	pushl $0
	pushl $47
	jmp _alltraps
.globl intr_vec47
intr_vec48:
	cli
	pushl $0
	pushl $48
	jmp _alltraps
.globl intr_vec48
intr_vec49:
	cli
	pushl $0
	pushl $49
	jmp _alltraps
.globl intr_vec49
intr_vec50:
	cli
	pushl $0
	pushl $50
	jmp _alltraps
.globl intr_vec50
intr_vec51:
	cli
	pushl $0
	pushl $51
	jmp _alltraps
.globl intr_vec51
intr_vec52:
	cli
	pushl $0
	pushl $52
	jmp _alltraps
.globl intr_vec52
intr_vec53:
	cli
	pushl $0
	pushl $53
	jmp _alltraps
.globl intr_vec53
intr_vec54:
	cli
	pushl $0
	pushl $54
	jmp _alltraps
.globl intr_vec54
intr_vec55:
	cli
	pushl $0
	pushl $55
	jmp _alltraps
.globl intr_vec55
intr_vec56:
	cli
	pushl $0
	pushl $56
	jmp _alltraps
.globl intr_vec56
intr_vec57:
	cli
	pushl $0
	pushl $57
	jmp _alltraps
.globl intr_vec57
intr_vec58:
	cli
	pushl $0
	pushl $58
	jmp _alltraps
.globl intr_vec58
intr_vec59:
	cli
	pushl $0
	pushl $59
	jmp _alltraps
.globl intr_vec59
intr_vec60:
	cli
	pushl $0
	pushl $60
	jmp _alltraps
.globl intr_vec60
intr_vec61:
	cli
	pushl $0
	pushl $61
	jmp _alltraps
.globl intr_vec61
intr_vec62:
	cli
	pushl $0
	pushl $62
	jmp _alltraps
.globl intr_vec62
intr_vec63:
	cli
	pushl $0
	pushl $63
	jmp _alltraps
.globl intr_vec63
intr_vec64:
	cli
	pushl $0
	pushl $64
	jmp _alltraps
.globl intr_vec64
intr_vec65:
	cli
	pushl $0
	pushl $65
	jmp _alltraps
.globl intr_vec65
intr_vec66:
	cli
	pushl $0
	pushl $66
	jmp _alltraps
.globl intr_vec66
intr_vec67:
	cli
	pushl $0
	pushl $67
	jmp _alltraps
.globl intr_vec67
intr_vec68:
	cli
	pushl $0
	pushl $68
	jmp _alltraps
.globl intr_vec68
intr_vec69:
	cli
	pushl $0
	pushl $69
	jmp _alltraps
.globl intr_vec69
intr_vec70:
	cli
	pushl $0
	pushl $70
	jmp _alltraps
.globl intr_vec70
intr_vec71:
	cli
	pushl $0
	pushl $71
	jmp _alltraps
.globl intr_vec71
intr_vec72:
	cli
	pushl $0
	pushl $72
	jmp _alltraps
.globl intr_vec72
intr_vec73:
	cli
	pushl $0
	pushl $73
	jmp _alltraps
.globl intr_vec73
intr_vec74:
	cli
	pushl $0
	pushl $74
	jmp _alltraps
.globl intr_vec74
intr_vec75:
	cli
	pushl $0
	pushl $75
	jmp _alltraps
.globl intr_vec75
intr_vec76:
	cli
	pushl $0
	pushl $76
	jmp _alltraps
.globl intr_vec76
intr_vec77:
	cli
	pushl $0
	pushl $77
	jmp _alltraps
.globl intr_vec77
intr_vec78:
	cli
	pushl $0
	pushl $78
	jmp _alltraps
.globl intr_vec78
intr_vec79:
	cli
	pushl $0
	pushl $79
	jmp _alltraps
.globl intr_vec79
intr_vec80:
	cli
	pushl $0
	pushl $80
	jmp _alltraps
.globl intr_vec80
intr_vec81:
	cli
	pushl $0
	pushl $81
	jmp _alltraps
.globl intr_vec81
intr_vec82:
	cli
	pushl $0
	pushl $82
	jmp _alltraps
.globl intr_vec82
intr_vec83:
	cli
	pushl $0
	pushl $83
	jmp _alltraps
.globl intr_vec83
intr_vec84:
	cli
	pushl $0
	pushl $84
	jmp _alltraps
.globl intr_vec84
intr_vec85:
	cli
	pushl $0
	pushl $85
	jmp _alltraps
.globl intr_vec85
intr_vec86:
	cli
	pushl $0
	pushl $86
	jmp _alltraps
.globl intr_vec86
intr_vec87:
	cli
	pushl $0
	pushl $87
	jmp _alltraps
.globl intr_vec87
intr_vec88:
	cli
	pushl $0
	pushl $88
	jmp _alltraps
.globl intr_vec88
intr_vec89:
	cli
	pushl $0
	pushl $89
	jmp _alltraps
.globl intr_vec89
intr_vec90:
	cli
	pushl $0
	pushl $90
	jmp _alltraps
.globl intr_vec90
intr_vec91:
	cli
	pushl $0
	pushl $91
	jmp _alltraps
.globl intr_vec91
intr_vec92:
	cli
	pushl $0
	pushl $92
	jmp _alltraps
.globl intr_vec92
intr_vec93:
	cli
	pushl $0
	pushl $93
	jmp _alltraps
.globl intr_vec93
intr_vec94:
	cli
	pushl $0
	pushl $94
	jmp _alltraps
.globl intr_vec94
intr_vec95:
	cli
	pushl $0
	pushl $95
	jmp _alltraps
.globl intr_vec95
intr_vec96:
	cli
	pushl $0
	pushl $96
	jmp _alltraps
.globl intr_vec96
intr_vec97:
	cli
	pushl $0
	pushl $97
	jmp _alltraps
.globl intr_vec97
intr_vec98:
	cli
	pushl $0
	pushl $98
	jmp _alltraps
.globl intr_vec98
intr_vec99:
	cli
	pushl $0
	pushl $99
	jmp _alltraps
.globl intr_vec99
intr_vec100:
	cli
	pushl $0
	pushl $100
	jmp _alltraps
.globl intr_vec100
intr_vec101:
	cli
	pushl $0
	pushl $101
	jmp _alltraps
.globl intr_vec101
intr_vec102:
	cli
	pushl $0
	pushl $102
	jmp _alltraps
.globl intr_vec102
intr_vec103:
	cli
	pushl $0
	pushl $103
	jmp _alltraps
.globl intr_vec103
intr_vec104:
	cli
	pushl $0
	pushl $104
	jmp _alltraps
.globl intr_vec104
intr_vec105:
	cli
	pushl $0
	pushl $105
	jmp _alltraps
.globl intr_vec105
intr_vec106:
	cli
	pushl $0
	pushl $106
	jmp _alltraps
.globl intr_vec106
intr_vec107:
	cli
	pushl $0
	pushl $107
	jmp _alltraps
.globl intr_vec107
intr_vec108:
	cli
	pushl $0
	pushl $108
	jmp _alltraps
.globl intr_vec108
intr_vec109:
	cli
	pushl $0
	pushl $109
	jmp _alltraps
.globl intr_vec109
intr_vec110:
	cli
	pushl $0
	pushl $110
	jmp _alltraps
.globl intr_vec110
intr_vec111:
	cli
	pushl $0
	pushl $111
	jmp _alltraps
.globl intr_vec111
intr_vec112:
	cli
	pushl $0
	pushl $112
	jmp _alltraps
.globl intr_vec112
intr_vec113:
	cli
	pushl $0
	pushl $113
	jmp _alltraps
.globl intr_vec113
intr_vec114:
	cli
	pushl $0
	pushl $114
	jmp _alltraps
.globl intr_vec114
intr_vec115:
	cli
	pushl $0
	pushl $115
	jmp _alltraps
.globl intr_vec115
intr_vec116:
	cli
	pushl $0
	pushl $116
	jmp _alltraps
.globl intr_vec116
intr_vec117:
	cli
	pushl $0
	pushl $117
	jmp _alltraps
.globl intr_vec117
intr_vec118:
	cli
	pushl $0
	pushl $118
	jmp _alltraps
.globl intr_vec118
intr_vec119:
	cli
	pushl $0
	pushl $119
	jmp _alltraps
.globl intr_vec119
intr_vec120:
	cli
	pushl $0
	pushl $120
	jmp _alltraps
.globl intr_vec120
intr_vec121:
	cli
	pushl $0
	pushl $121
	jmp _alltraps
.globl intr_vec121
intr_vec122:
	cli
	pushl $0
	pushl $122
	jmp _alltraps
.globl intr_vec122
intr_vec123:
	cli
	pushl $0
	pushl $123
	jmp _alltraps
.globl intr_vec123
intr_vec124:
	cli
	pushl $0
	pushl $124
	jmp _alltraps
.globl intr_vec124
intr_vec125:
	cli
	pushl $0
	pushl $125
	jmp _alltraps
.globl intr_vec125
intr_vec126:
	cli
	pushl $0
	pushl $126
	jmp _alltraps
.globl intr_vec126
intr_vec127:
	cli
	pushl $0
	pushl $127
	jmp _alltraps
.globl intr_vec127
intr_vec128:
	cli
	pushl $0
	pushl $128
	jmp _alltraps
.globl intr_vec128
intr_vec129:
	cli
	pushl $0
	pushl $129
	jmp _alltraps
.globl intr_vec129
intr_vec130:
	cli
	pushl $0
	pushl $130
	jmp _alltraps
.globl intr_vec130
intr_vec131:
	cli
	pushl $0
	pushl $131
	jmp _alltraps
.globl intr_vec131
intr_vec132:
	cli
	pushl $0
	pushl $132
	jmp _alltraps
.globl intr_vec132
intr_vec133:
	cli
	pushl $0
	pushl $133
	jmp _alltraps
.globl intr_vec133
intr_vec134:
	cli
	pushl $0
	pushl $134
	jmp _alltraps
.globl intr_vec134
intr_vec135:
	cli
	pushl $0
	pushl $135
	jmp _alltraps
.globl intr_vec135
intr_vec136:
	cli
	pushl $0
	pushl $136
	jmp _alltraps
.globl intr_vec136
intr_vec137:
	cli
	pushl $0
	pushl $137
	jmp _alltraps
.globl intr_vec137
intr_vec138:
	cli
	pushl $0
	pushl $138
	jmp _alltraps
.globl intr_vec138
intr_vec139:
	cli
	pushl $0
	pushl $139
	jmp _alltraps
.globl intr_vec139
intr_vec140:
	cli
	pushl $0
	pushl $140
	jmp _alltraps
.globl intr_vec140
intr_vec141:
	cli
	pushl $0
	pushl $141
	jmp _alltraps
.globl intr_vec141
intr_vec142:
	cli
	pushl $0
	pushl $142
	jmp _alltraps
.globl intr_vec142
intr_vec143:
	cli
	pushl $0
	pushl $143
	jmp _alltraps
.globl intr_vec143
intr_vec144:
	cli
	pushl $0
	pushl $144
	jmp _alltraps
.globl intr_vec144
intr_vec145:
	cli
	pushl $0
	pushl $145
	jmp _alltraps
.globl intr_vec145
intr_vec146:
	cli
	pushl $0
	pushl $146
	jmp _alltraps
.globl intr_vec146
intr_vec147:
	cli
	pushl $0
	pushl $147
	jmp _alltraps
.globl intr_vec147
intr_vec148:
	cli
	pushl $0
	pushl $148
	jmp _alltraps
.globl intr_vec148
intr_vec149:
	cli
	pushl $0
	pushl $149
	jmp _alltraps
.globl intr_vec149
intr_vec150:
	cli
	pushl $0
	pushl $150
	jmp _alltraps
.globl intr_vec150
intr_vec151:
	cli
	pushl $0
	pushl $151
	jmp _alltraps
.globl intr_vec151
intr_vec152:
	cli
	pushl $0
	pushl $152
	jmp _alltraps
.globl intr_vec152
intr_vec153:
	cli
	pushl $0
	pushl $153
	jmp _alltraps
.globl intr_vec153
intr_vec154:
	cli
	pushl $0
	pushl $154
	jmp _alltraps
.globl intr_vec154
intr_vec155:
	cli
	pushl $0
	pushl $155
	jmp _alltraps
.globl intr_vec155
intr_vec156:
	cli
	pushl $0
	pushl $156
	jmp _alltraps
.globl intr_vec156
intr_vec157:
	cli
	pushl $0
	pushl $157
	jmp _alltraps
.globl intr_vec157
intr_vec158:
	cli
	pushl $0
	pushl $158
	jmp _alltraps
.globl intr_vec158
intr_vec159:
	cli
	pushl $0
	pushl $159
	jmp _alltraps
.globl intr_vec159
intr_vec160:
	cli
	pushl $0
	pushl $160
	jmp _alltraps
.globl intr_vec160
intr_vec161:
	cli
	pushl $0
	pushl $161
	jmp _alltraps
.globl intr_vec161
intr_vec162:
	cli
	pushl $0
	pushl $162
	jmp _alltraps
.globl intr_vec162
intr_vec163:
	cli
	pushl $0
	pushl $163
	jmp _alltraps
.globl intr_vec163
intr_vec164:
	cli
	pushl $0
	pushl $164
	jmp _alltraps
.globl intr_vec164
intr_vec165:
	cli
	pushl $0
	pushl $165
	jmp _alltraps
.globl intr_vec165
intr_vec166:
	cli
	pushl $0
	pushl $166
	jmp _alltraps
.globl intr_vec166
intr_vec167:
	cli
	pushl $0
	pushl $167
	jmp _alltraps
.globl intr_vec167
intr_vec168:
	cli
	pushl $0
	pushl $168
	jmp _alltraps
.globl intr_vec168
intr_vec169:
	cli
	pushl $0
	pushl $169
	jmp _alltraps
.globl intr_vec169
intr_vec170:
	cli
	pushl $0
	pushl $170
	jmp _alltraps
.globl intr_vec170
intr_vec171:
	cli
	pushl $0
	pushl $171
	jmp _alltraps
.globl intr_vec171
intr_vec172:
	cli
	pushl $0
	pushl $172
	jmp _alltraps
.globl intr_vec172
intr_vec173:
	cli
	pushl $0
	pushl $173
	jmp _alltraps
.globl intr_vec173
intr_vec174:
	cli
	pushl $0
	pushl $174
	jmp _alltraps
.globl intr_vec174
intr_vec175:
	cli
	pushl $0
	pushl $175
	jmp _alltraps
.globl intr_vec175
intr_vec176:
	cli
	pushl $0
	pushl $176
	jmp _alltraps
.globl intr_vec176
intr_vec177:
	cli
	pushl $0
	pushl $177
	jmp _alltraps
.globl intr_vec177
intr_vec178:
	cli
	pushl $0
	pushl $178
	jmp _alltraps
.globl intr_vec178
intr_vec179:
	cli
	pushl $0
	pushl $179
	jmp _alltraps
.globl intr_vec179
intr_vec180:
	cli
	pushl $0
	pushl $180
	jmp _alltraps
.globl intr_vec180
intr_vec181:
	cli
	pushl $0
	pushl $181
	jmp _alltraps
.globl intr_vec181
intr_vec182:
	cli
	pushl $0
	pushl $182
	jmp _alltraps
.globl intr_vec182
intr_vec183:
	cli
	pushl $0
	pushl $183
	jmp _alltraps
.globl intr_vec183
intr_vec184:
	cli
	pushl $0
	pushl $184
	jmp _alltraps
.globl intr_vec184
intr_vec185:
	cli
	pushl $0
	pushl $185
	jmp _alltraps
.globl intr_vec185
intr_vec186:
	cli
	pushl $0
	pushl $186
	jmp _alltraps
.globl intr_vec186
intr_vec187:
	cli
	pushl $0
	pushl $187
	jmp _alltraps
.globl intr_vec187
intr_vec188:
	cli
	pushl $0
	pushl $188
	jmp _alltraps
.globl intr_vec188
intr_vec189:
	cli
	pushl $0
	pushl $189
	jmp _alltraps
.globl intr_vec189
intr_vec190:
	cli
	pushl $0
	pushl $190
	jmp _alltraps
.globl intr_vec190
intr_vec191:
	cli
	pushl $0
	pushl $191
	jmp _alltraps
.globl intr_vec191
intr_vec192:
	cli
	pushl $0
	pushl $192
	jmp _alltraps
.globl intr_vec192
intr_vec193:
	cli
	pushl $0
	pushl $193
	jmp _alltraps
.globl intr_vec193
intr_vec194:
	cli
	pushl $0
	pushl $194
	jmp _alltraps
.globl intr_vec194
intr_vec195:
	cli
	pushl $0
	pushl $195
	jmp _alltraps
.globl intr_vec195
intr_vec196:
	cli
	pushl $0
	pushl $196
	jmp _alltraps
.globl intr_vec196
intr_vec197:
	cli
	pushl $0
	pushl $197
	jmp _alltraps
.globl intr_vec197
intr_vec198:
	cli
	pushl $0
	pushl $198
	jmp _alltraps
.globl intr_vec198
intr_vec199:
	cli
	pushl $0
	pushl $199
	jmp _alltraps
.globl intr_vec199
intr_vec200:
	cli
	pushl $0
	pushl $200
	jmp _alltraps
.globl intr_vec200
intr_vec201:
	cli
	pushl $0
	pushl $201
	jmp _alltraps
.globl intr_vec201
intr_vec202:
	cli
	pushl $0
	pushl $202
	jmp _alltraps
.globl intr_vec202
intr_vec203:
	cli
	pushl $0
	pushl $203
	jmp _alltraps
.globl intr_vec203
intr_vec204:
	cli
	pushl $0
	pushl $204
	jmp _alltraps
.globl intr_vec204
intr_vec205:
	cli
	pushl $0
	pushl $205
	jmp _alltraps
.globl intr_vec205
intr_vec206:
	cli
	pushl $0
	pushl $206
	jmp _alltraps
.globl intr_vec206
intr_vec207:
	cli
	pushl $0
	pushl $207
	jmp _alltraps
.globl intr_vec207
intr_vec208:
	cli
	pushl $0
	pushl $208
	jmp _alltraps
.globl intr_vec208
intr_vec209:
	cli
	pushl $0
	pushl $209
	jmp _alltraps
.globl intr_vec209
intr_vec210:
	cli
	pushl $0
	pushl $210
	jmp _alltraps
.globl intr_vec210
intr_vec211:
	cli
	pushl $0
	pushl $211
	jmp _alltraps
.globl intr_vec211
intr_vec212:
	cli
	pushl $0
	pushl $212
	jmp _alltraps
.globl intr_vec212
intr_vec213:
	cli
	pushl $0
	pushl $213
	jmp _alltraps
.globl intr_vec213
intr_vec214:
	cli
	pushl $0
	pushl $214
	jmp _alltraps
.globl intr_vec214
intr_vec215:
	cli
	pushl $0
	pushl $215
	jmp _alltraps
.globl intr_vec215
intr_vec216:
	cli
	pushl $0
	pushl $216
	jmp _alltraps
.globl intr_vec216
intr_vec217:
	cli
	pushl $0
	pushl $217
	jmp _alltraps
.globl intr_vec217
intr_vec218:
	cli
	pushl $0
	pushl $218
	jmp _alltraps
.globl intr_vec218
intr_vec219:
	cli
	pushl $0
	pushl $219
	jmp _alltraps
.globl intr_vec219
intr_vec220:
	cli
	pushl $0
	pushl $220
	jmp _alltraps
.globl intr_vec220
intr_vec221:
	cli
	pushl $0
	pushl $221
	jmp _alltraps
.globl intr_vec221
intr_vec222:
	cli
	pushl $0
	pushl $222
	jmp _alltraps
.globl intr_vec222
intr_vec223:
	cli
	pushl $0
	pushl $223
	jmp _alltraps
.globl intr_vec223
intr_vec224:
	cli
	pushl $0
	pushl $224
	jmp _alltraps
.globl intr_vec224
intr_vec225:
	cli
	pushl $0
	pushl $225
	jmp _alltraps
.globl intr_vec225
intr_vec226:
	cli
	pushl $0
	pushl $226
	jmp _alltraps
.globl intr_vec226
intr_vec227:
	cli
	pushl $0
	pushl $227
	jmp _alltraps
.globl intr_vec227
intr_vec228:
	cli
	pushl $0
	pushl $228
	jmp _alltraps
.globl intr_vec228
intr_vec229:
	cli
	pushl $0
	pushl $229
	jmp _alltraps
.globl intr_vec229
intr_vec230:
	cli
	pushl $0
	pushl $230
	jmp _alltraps
.globl intr_vec230
intr_vec231:
	cli
	pushl $0
	pushl $231
	jmp _alltraps
.globl intr_vec231
intr_vec232:
	cli
	pushl $0
	pushl $232
	jmp _alltraps
.globl intr_vec232
intr_vec233:
	cli
	pushl $0
	pushl $233
	jmp _alltraps
.globl intr_vec233
intr_vec234:
	cli
	pushl $0
	pushl $234
	jmp _alltraps
.globl intr_vec234
intr_vec235:
	cli
	pushl $0
	pushl $235
	jmp _alltraps
.globl intr_vec235
intr_vec236:
	cli
	pushl $0
	pushl $236
	jmp _alltraps
.globl intr_vec236
intr_vec237:
	cli
	pushl $0
	pushl $237
	jmp _alltraps
.globl intr_vec237
intr_vec238:
	cli
	pushl $0
	pushl $238
	jmp _alltraps
.globl intr_vec238
intr_vec239:
	cli
	pushl $0
	pushl $239
	jmp _alltraps
.globl intr_vec239
intr_vec240:
	cli
	pushl $0
	pushl $240
	jmp _alltraps
.globl intr_vec240
intr_vec241:
	cli
	pushl $0
	pushl $241
	jmp _alltraps
.globl intr_vec241
intr_vec242:
	cli
	pushl $0
	pushl $242
	jmp _alltraps
.globl intr_vec242
intr_vec243:
	cli
	pushl $0
	pushl $243
	jmp _alltraps
.globl intr_vec243
intr_vec244:
	cli
	pushl $0
	pushl $244
	jmp _alltraps
.globl intr_vec244
intr_vec245:
	cli
	pushl $0
	pushl $245
	jmp _alltraps
.globl intr_vec245
intr_vec246:
	cli
	pushl $0
	pushl $246
	jmp _alltraps
.globl intr_vec246
intr_vec247:
	cli
	pushl $0
	pushl $247
	jmp _alltraps
.globl intr_vec247
intr_vec248:
	cli
	pushl $0
	pushl $248
	jmp _alltraps
.globl intr_vec248
intr_vec249:
	cli
	pushl $0
	pushl $249
	jmp _alltraps
.globl intr_vec249
intr_vec250:
	cli
	pushl $0
	pushl $250
	jmp _alltraps
.globl intr_vec250
intr_vec251:
	cli
	pushl $0
	pushl $251
	jmp _alltraps
.globl intr_vec251
intr_vec252:
	cli
	pushl $0
	pushl $252
	jmp _alltraps
.globl intr_vec252
intr_vec253:
	cli
	pushl $0
	pushl $253
	jmp _alltraps
.globl intr_vec253
intr_vec254:
	cli
	pushl $0
	pushl $254
	jmp _alltraps
.globl intr_vec254
intr_vec255:
	cli
	pushl $0
	pushl $255
	jmp _alltraps
.globl intr_vec255

.data
.globl _intr_vec
_intr_vec:
	.long intr_vec0
	.long intr_vec1
	.long intr_vec2
	.long intr_vec3
	.long intr_vec4
	.long intr_vec5
	.long intr_vec6
	.long intr_vec7
	.long intr_vec8
	.long intr_vec9
	.long intr_vec10
	.long intr_vec11
	.long intr_vec12
	.long intr_vec13
	.long intr_vec14
	.long intr_vec15
	.long intr_vec16
	.long intr_vec17
	.long intr_vec18
	.long intr_vec19
	.long intr_vec20
	.long intr_vec21
	.long intr_vec22
	.long intr_vec23
	.long intr_vec24
	.long intr_vec25
	.long intr_vec26
	.long intr_vec27
	.long intr_vec28
	.long intr_vec29
	.long intr_vec30
	.long intr_vec31
	.long intr_vec32
	.long intr_vec33
	.long intr_vec34
	.long intr_vec35
	.long intr_vec36
	.long intr_vec37
	.long intr_vec38
	.long intr_vec39
	.long intr_vec40
	.long intr_vec41
	.long intr_vec42
	.long intr_vec43
	.long intr_vec44
	.long intr_vec45
	.long intr_vec46
	.long intr_vec47
	.long intr_vec48
	.long intr_vec49
	.long intr_vec50
	.long intr_vec51
	.long intr_vec52
	.long intr_vec53
	.long intr_vec54
	.long intr_vec55
	.long intr_vec56
	.long intr_vec57
	.long intr_vec58
	.long intr_vec59
	.long intr_vec60
	.long intr_vec61
	.long intr_vec62
	.long intr_vec63
	.long intr_vec64
	.long intr_vec65
	.long intr_vec66
	.long intr_vec67
	.long intr_vec68
	.long intr_vec69
	.long intr_vec70
	.long intr_vec71
	.long intr_vec72
	.long intr_vec73
	.long intr_vec74
	.long intr_vec75
	.long intr_vec76
	.long intr_vec77
	.long intr_vec78
	.long intr_vec79
	.long intr_vec80
	.long intr_vec81
	.long intr_vec82
	.long intr_vec83
	.long intr_vec84
	.long intr_vec85
	.long intr_vec86
	.long intr_vec87
	.long intr_vec88
	.long intr_vec89
	.long intr_vec90
	.long intr_vec91
	.long intr_vec92
	.long intr_vec93
	.long intr_vec94
	.long intr_vec95
	.long intr_vec96
	.long intr_vec97
	.long intr_vec98
	.long intr_vec99
	.long intr_vec100
	.long intr_vec101
	.long intr_vec102
	.long intr_vec103
	.long intr_vec104
	.long intr_vec105
	.long intr_vec106
	.long intr_vec107
	.long intr_vec108
	.long intr_vec109
	.long intr_vec110
	.long intr_vec111
	.long intr_vec112
	.long intr_vec113
	.long intr_vec114
	.long intr_vec115
	.long intr_vec116
	.long intr_vec117
	.long intr_vec118
	.long intr_vec119
	.long intr_vec120
	.long intr_vec121
	.long intr_vec122
	.long intr_vec123
	.long intr_vec124
	.long intr_vec125
	.long intr_vec126
	.long intr_vec127
	.long intr_vec128
	.long intr_vec129
	.long intr_vec130
	.long intr_vec131
	.long intr_vec132
	.long intr_vec133
	.long intr_vec134
	.long intr_vec135
	.long intr_vec136
	.long intr_vec137
	.long intr_vec138
	.long intr_vec139
	.long intr_vec140
	.long intr_vec141
	.long intr_vec142
	.long intr_vec143
	.long intr_vec144
	.long intr_vec145
	.long intr_vec146
	.long intr_vec147
	.long intr_vec148
	.long intr_vec149
	.long intr_vec150
	.long intr_vec151
	.long intr_vec152
	.long intr_vec153
	.long intr_vec154
	.long intr_vec155
	.long intr_vec156
	.long intr_vec157
	.long intr_vec158
	.long intr_vec159
	.long intr_vec160
	.long intr_vec161
	.long intr_vec162
	.long intr_vec163
	.long intr_vec164
	.long intr_vec165
	.long intr_vec166
	.long intr_vec167
	.long intr_vec168
	.long intr_vec169
	.long intr_vec170
	.long intr_vec171
	.long intr_vec172
	.long intr_vec173
	.long intr_vec174
	.long intr_vec175
	.long intr_vec176
	.long intr_vec177
	.long intr_vec178
	.long intr_vec179
	.long intr_vec180
	.long intr_vec181
	.long intr_vec182
	.long intr_vec183
	.long intr_vec184
	.long intr_vec185
	.long intr_vec186
	.long intr_vec187
	.long intr_vec188
	.long intr_vec189
	.long intr_vec190
	.long intr_vec191
	.long intr_vec192
	.long intr_vec193
	.long intr_vec194
	.long intr_vec195
	.long intr_vec196
	.long intr_vec197
	.long intr_vec198
	.long intr_vec199
	.long intr_vec200
	.long intr_vec201
	.long intr_vec202
	.long intr_vec203
	.long intr_vec204
	.long intr_vec205
	.long intr_vec206
	.long intr_vec207
	.long intr_vec208
	.long intr_vec209
	.long intr_vec210
	.long intr_vec211
	.long intr_vec212
	.long intr_vec213
	.long intr_vec214
	.long intr_vec215
	.long intr_vec216
	.long intr_vec217
	.long intr_vec218
	.long intr_vec219
	.long intr_vec220
	.long intr_vec221
	.long intr_vec222
	.long intr_vec223
	.long intr_vec224
	.long intr_vec225
	.long intr_vec226
	.long intr_vec227
	.long intr_vec228
	.long intr_vec229
	.long intr_vec230
	.long intr_vec231
	.long intr_vec232
	.long intr_vec233
	.long intr_vec234
	.long intr_vec235
	.long intr_vec236
	.long intr_vec237
	.long intr_vec238
	.long intr_vec239
	.long intr_vec240
	.long intr_vec241
	.long intr_vec242
	.long intr_vec243
	.long intr_vec244
	.long intr_vec245
	.long intr_vec246
	.long intr_vec247
	.long intr_vec248
	.long intr_vec249
	.long intr_vec250
	.long intr_vec251
	.long intr_vec252
	.long intr_vec253
	.long intr_vec254
	.long intr_vec255
